version: '3.9'

services:
  rstudio:
    image: rocker/verse:latest
    container_name: shiny_parquet_demo
    ports:
      - "8787:8787"  # RStudio
      - "3838:3838"  # Shiny app
    environment:
      - PASSWORD=rstudiodemo
    volumes:
      - ./shiny_parquet.R:/home/rstudio/shiny_parquet.R
      - ./output:/home/rstudio/output
      - ./data:/home/rstudio/data
    working_dir: /home/rstudio
    init: true
    entrypoint: /bin/bash
    command: >
      -c "
      apt-get -y update && \
      apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev && \
      Rscript -e 'install.packages(c(\"leaflet\", \"DT\", \"arrow\", \"sf\", \"dplyr\", \"leaflet.extras\", \"shiny\"))' && \
      Rscript /home/rstudio/shiny_parquet.R
      "



# Usage:
# Run `docker-compose up` to start the container and access RStudio.
# Access RStudio at http://localhost:8787 with username 'rstudio' and password 'demo'.
# Edit the script in RStudio and render it manually.
