name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up node, marp-cli
      run: sudo apt-get update && sudo apt-get install -y nodejs npm && \
          sudo npm install -g marp-cli && \
          sudo npm install -g @marp-team/marp-cli

    - name: Build HTML and PDF
      run: make all

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/
        git commit -m "Update documentation [skip ci]" || echo "No changes to commit"
        git push
